name: Check

on:
  push:
    branches-ignore:
      - master

  pull_request:
    branches-ignore:
      - master

jobs:
  jvm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.2.2
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/master' }}

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Configure JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Run all checks
        run: ./gradlew check --stacktrace
